const DATA_FETCHING = 'DATA_FETCHING'
const VIDEO_RESULTS_FETCHED = 'VIDEO_RESULTS_FETCHED'
const NEW_USER_CONTEXT = 'NEW_USER_CONTEXT'
const UNRESOLVED_COORDINATES_CONTEXT = 'UNRESOLVED_COORDS'
const GRAY_COLOR = '#E5E7E9'
export {
    DATA_FETCHING,
    VIDEO_RESULTS_FETCHED,
    NEW_USER_CONTEXT,
    UNRESOLVED_COORDINATES_CONTEXT,
    GRAY_COLOR
}